---
- name: Configure BIG-IP
  hosts: apic
  connection: local
  gather_facts: no
  vars:
    use_ssl: yes
    validate_certs: false
  vars_files:
    - "bigip_variables.yml"

  tasks:

  - name: Setting up provider values
    set_fact:
     provider:
      server: "{{ bigip_ip }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      server_port: "443"
      validate_certs: "False"

  - name: Create pool
    bigip_pool:
      provider: "{{ provider }}"
      name: "{{ pool_name }}"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"

  - name: Add Virtual Server
    bigip_virtual_server:
      provider: "{{ provider }}"
      name: "{{ vip_name }}"
      destination: "{{ vip_ip }}"
      port: "{{ vip_port }}"
      profiles:
      - http
      pool: "{{ pool_name }}"
      snat: "automap"
  
